config/routes.rb
Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :cat_rental_requests, only: [:index, :show, :new, :create, :edit, :update, :destroy] 

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :birth_date, :color, :name, :sex, presence: true
  validates :sex, length: {is: 1}
  validate :validates_sex

  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest

  def validates_sex
    self.errors[:sex] << "Invalid sex" unless self.sex.upcase == "M" || self.sex.upcase == "F"
  end

  def age
    Time.now.year - self.birth_date.year
  end


end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: ['PENDING', 'APPROVED', 'DENIED'] }
  validate :overlapping_approved_requests

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat,
    dependent: :destroy


  def approve!
    self.transaction do
      unless overlapping_approved_requests
        self.status = 'APPROVED'
      else
        deny!
      end
      self.save
    end
  end

  def deny!
    self.status = 'DENIED'
  end

  def overlapping_approved_requests
    # look up other request, and check to see their start_date and end_date
    # if they conflict, false, else true
    requests = CatRentalRequest.where(cat_id: self.cat_id)
    requests = requests.reject { |el| el.id == self.id  }
    self.errors[:requests] << "Overlapping approved requests" if
      requests.any? { |req| req.start_date.between?(self.start_date, self.end_date) &&
                            req.status == "APPROVED" && self.status == "APPROVED" }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def index
    @cat_rental_requests = CatRentalRequest.all
    render :index
  end

  def new
    @cat_rental_request = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  # def edit
  #   @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
  #   render :edit
  # end
  #
  # def update
  #   @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
  #
  #   if @cat_rental_request.update
  #     redirect_to cat_rental_request_url(@cat_rental_request)
  #   else
  #     render :edit
  #   end
  # end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      flash[:notice] = "Created #{@cat_rental_request.cat_id}"
      redirect_to cat_rental_request_url(@cat_rental_request)
    else
      render json: @cat_rental_request.errors.full_messages, status: :unprocessable_entity
    end
  end

  def show
    @cat_rental_requests = CatRentalRequest.all
    @sorted = @cat_rental_requests.to_a.sort{ |el1, el2| el1.start_date <=> el2.start_date}
    render json: @sorted
  end

  def age
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    @cat_rental_request.age
  end

  private
  def cat_rental_request_params
    params[:cat_rental_request].permit(:cat_id, :start_date, :end_date, :status)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      flash[:notice] = "Created #{@cat.name}"
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  # def show
  #   @cat = Cat.find_by(id: params[:id])
  #   render :table
  # end

  def show
    @cat = Cat.find_by(id: params[:id])
    @cat_rental_requests = CatRentalRequest.all
    render :show
  end

  def age
    @cat = Cat.find_by(id: params[:id])
    @cat.age
  end

  private
  def cat_params
    params[:cat].permit(:name, :color, :sex, :birth_date, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

app/helpers/cats_controller_helper.rb
module CatsControllerHelper
end

app/views/cat_rental_requests/index.html.erb
<% @cat_rental_requests.each do |req| %>
  <ul>
    <li>Name: <%= Cat.find_by(id: req.cat_id).name %></li>
    <li>Start Date: <%= req.start_date %></li>
    <li>End Date: <%= req.end_date %></li>
  </ul>
<% end %>

app/views/cat_rental_requests/new.html.erb
<!--
  Things to change:
    - action (done!)
    - hidden input patch (done!)
    - pre-filled values (done!)
    - submit button (done!)
-->


<% action_url = cat_rental_requests_url %>

<form action="<%= action_url %>" method="post">


  <label for="cat_rental_request_cat_id">Cat</label>
  <select id="cat_rental_request_cat_id" name="cat_rental_request[cat_id]">
    <option value="Select Cat" disabled="true" selected="true">Select Cat</option>
    <% @cats.each do |cat| %>
      <option value= '<%= cat.id %>'> <%= cat.name %> </option>
    <% end %>
  </select>


  <!-- <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option value="Select Color" disabled="true" selected="true">Select Color</option>
    <option value="Black">Black</option>
    <option value="White">White</option>
    <option value="Red">Red</option>
  </select> -->


  <br>

  <label for="start_date">Start Date</label>
  <input id="start_date" type="date" name="cat_rental_request[start_date]" value="cat_rental_request.start_date">

  <label for="end_date">End Date</label>
  <input id="end_date" type="date" name="cat_rental_request[end_date]" value="cat_rental_request.end_date">

  <br>

  <input type="submit" value="<%= action = 'add cat rental request'%>">
</form>

app/views/cats/_form.html.erb
<!--
  Things to change:
    - action (done!)
    - hidden input patch (done!)
    - pre-filled values (done!)
    - submit button (done!)
-->

<% if action == :edit %>
  <% action_url = cat_url(cat)%>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="string" name="cat[name]" value="<%= cat.name %>">

  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option value="Select Color" disabled="true" selected="true">Select Color</option>
    <option value="Black">Black</option>
    <option value="White">White</option>
    <option value="Red">Red</option>
    <option value="Orange">Orange</option>
  </select>

  <br>

  <label for="sex">Sex</label>
  M<input type="radio" name="cat[sex]" value="M">
  F<input type="radio" name="cat[sex]" value="F">

  <br>

  <label for="birth_date">Birthdate</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date%>">

  <br>

  <label for="description">Description</label>
  <textarea name="cat[description]">
    <%= cat.description %>
  </textarea>

  <br><br>

  <input type="submit" value="<%= action == :edit ? 'update cat' : 'add cat'%>">
</form>

app/views/cats/edit.html.erb
<h1>Edit cat!</h1>

<!-- action: url to which we want to send data -->
<!-- method: http method that we want to use -->

<%= render 'form', action: :edit, cat: @cat %>

app/views/cats/index.html.erb
<body>
  <header>Welcome to the Cat Shelter!</header>
  <% @cats.each do |cat| %>
    <ul>
      <h1>Cat</h1>
      <li>Name: <a href="cats/<%= cat.id %>" > <%= cat.name %> </a></li>
      <li>Color: <%= cat.color %></li>
      <li>Sex: <%= cat.sex %></li>
      <li>Birthdate: <%= cat.birth_date %></li>
      <li>Description: <%= cat.description %></li>
    </ul>
  <% end %>

  <form action="cat_rental_requests/new">
    <input type="submit" value="Rent a Cat!" />
  </form>

  <br>

  <form action="cats/new">
    <input type="submit" value="Add a Cat!" />
  </form>
</body>

app/views/cats/new.html.erb
<h1>Add cat to Cats!</h1>

<!-- action: url to which we want to send data -->
<!-- method: http method that we want to use -->

<%= render 'form', action: :new, cat: @cat %>

app/views/cats/show.html.erb
<table>
  <tr>
    <th>Name:</th>
    <th><%= @cat.name %></th>
  </tr>
  <tr>
    <td>Color:</td>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <td>Sex:</td>
    <td><%= @cat.sex %></td>
  </tr>
  <tr>
    <td>Birthdate:</td>
    <td><%= @cat.birth_date %></td>
  </tr>
  <tr>
    <td>Description:</td>
    <td><%= @cat.description%></td>
  </tr>
</table>

<br>

<table>
  <% @rentals = CatRentalRequest.where(cat_id: @cat.id) %>
<% @rentals.sort {|el1, el2| el1.start_date <=> el2.start_date}.each do |rental| %>
  <%= "Start Date: #{rental.start_date}" %>
  <%= "End Date #{rental.end_date}" %>
  <br>
<% end %>
</table>

<br>

<form action="/cats">
  <input type="submit" value="All Cats" />
</form>

<form action="/cats/<%= @cat.id %>/edit">
  <input type="submit" value="Edit Cat" />
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>